server.port=8080
server.rmi.port=1099
server.rmi.serviceName=ConnectionsRegisterService
server.threadpool.size=10

puzzle.file.path=../data/Connections_Data.json
game.history.file.path=../data/game_history.json

game.time.second=300
game.pause.time.second=30
game.max.mistakes=4